export const users = [
  {
    avatar_url: "https://avatars.githubusercontent.com/u/24896512?v=4",
    bio: null,
    blog: "",
    company: null,
    created_at: "2017-01-03T15:05:12Z",
    email: "imrohit7604@gmail.com",
    emailError: false,
    events_url: "https://api.github.com/users/imrohit7604/events{/privacy}",
    followers: 0,
    followers_url: "https://api.github.com/users/imrohit7604/followers",
    following: 0,
    following_url:
      "https://api.github.com/users/imrohit7604/following{/other_user}",
    gists_url: "https://api.github.com/users/imrohit7604/gists{/gist_id}",
    gitHubUserName: "imrohit7604",
    gitHubUserNameError: false,
    gravatar_id: "",
    hireable: null,
    html_url: "https://github.com/imrohit7604",
    id: 24896512,
    location: null,
    login: "imrohit7604",
    name: "Rohit",
    nameError: false,
    node_id: "MDQ6VXNlcjI0ODk2NTEy",
    organizations_url: "https://api.github.com/users/imrohit7604/orgs",
    public_gists: 0,
    public_repos: 28,
    received_events_url:
      "https://api.github.com/users/imrohit7604/received_events",
    repos_url: "https://api.github.com/users/imrohit7604/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/imrohit7604/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/imrohit7604/subscriptions",
    twitter_username: null,
    type: "User",
    updated_at: "2021-08-06T12:51:35Z",
    url: "https://api.github.com/users/imrohit7604",
  },
  {
    login: "simonsmith",
    id: 360703,
    node_id: "MDQ6VXNlcjM2MDcwMw==",
    avatar_url: "https://avatars.githubusercontent.com/u/360703?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/simonsmith",
    html_url: "https://github.com/simonsmith",
    followers_url: "https://api.github.com/users/simonsmith/followers",
    following_url:
      "https://api.github.com/users/simonsmith/following{/other_user}",
    gists_url: "https://api.github.com/users/simonsmith/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/simonsmith/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/simonsmith/subscriptions",
    organizations_url: "https://api.github.com/users/simonsmith/orgs",
    repos_url: "https://api.github.com/users/simonsmith/repos",
    events_url: "https://api.github.com/users/simonsmith/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/simonsmith/received_events",
    type: "User",
    site_admin: false,
    name: "Simon Smith",
    company: "@treatwell",
    blog: "http://simonsmith.io",
    location: "London",
    email: null,
    hireable: true,
    bio: "Front end developer. All things CSS & JS. Core @suitcss",
    twitter_username: null,
    public_repos: 55,
    public_gists: 33,
    followers: 215,
    following: 46,
    created_at: "2010-08-11T09:09:16Z",
    updated_at: "2021-08-03T15:00:01Z",
  },
  {
    login: "ShivamJoker",
    id: 23727670,
    node_id: "MDQ6VXNlcjIzNzI3Njcw",
    avatar_url: "https://avatars.githubusercontent.com/u/23727670?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ShivamJoker",
    html_url: "https://github.com/ShivamJoker",
    followers_url: "https://api.github.com/users/ShivamJoker/followers",
    following_url:
      "https://api.github.com/users/ShivamJoker/following{/other_user}",
    gists_url: "https://api.github.com/users/ShivamJoker/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ShivamJoker/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ShivamJoker/subscriptions",
    organizations_url: "https://api.github.com/users/ShivamJoker/orgs",
    repos_url: "https://api.github.com/users/ShivamJoker/repos",
    events_url: "https://api.github.com/users/ShivamJoker/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ShivamJoker/received_events",
    type: "User",
    site_admin: false,
    name: "Shivam",
    company: null,
    blog: "creativeshi.com",
    location: "India, New Delhi",
    email: null,
    hireable: true,
    bio: "Creative Engineer 💻 | Married to JavaScript | Ex jQuery | Boyfriend of Typescript & React ⚛️",
    twitter_username: "ShivamJoker",
    public_repos: 100,
    public_gists: 11,
    followers: 316,
    following: 16,
    created_at: "2016-11-24T19:28:41Z",
    updated_at: "2021-08-22T13:58:43Z",
  },
  {
    login: "aryashah2k",
    id: 73865728,
    node_id: "MDQ6VXNlcjczODY1NzI4",
    avatar_url: "https://avatars.githubusercontent.com/u/73865728?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aryashah2k",
    html_url: "https://github.com/aryashah2k",
    followers_url: "https://api.github.com/users/aryashah2k/followers",
    following_url:
      "https://api.github.com/users/aryashah2k/following{/other_user}",
    gists_url: "https://api.github.com/users/aryashah2k/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/aryashah2k/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aryashah2k/subscriptions",
    organizations_url: "https://api.github.com/users/aryashah2k/orgs",
    repos_url: "https://api.github.com/users/aryashah2k/repos",
    events_url: "https://api.github.com/users/aryashah2k/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/aryashah2k/received_events",
    type: "User",
    site_admin: false,
    name: "Arya Shah",
    company: "@PatternHouse",
    blog: "https://www.linkedin.com/in/arya--shah/",
    location: "Mumbai, India",
    email: null,
    hireable: null,
    bio: "Computer Science Junior with Honors in Business Systems | Software Development Engineering | Machine Learning | ",
    twitter_username: "aryashah2k",
    public_repos: 36,
    public_gists: 0,
    followers: 1874,
    following: 3309,
    created_at: "2020-11-03T03:06:19Z",
    updated_at: "2021-08-08T05:50:32Z",
  },
  {
    login: "vinayakkulkarni",
    id: 19776877,
    node_id: "MDQ6VXNlcjE5Nzc2ODc3",
    avatar_url: "https://avatars.githubusercontent.com/u/19776877?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vinayakkulkarni",
    html_url: "https://github.com/vinayakkulkarni",
    followers_url: "https://api.github.com/users/vinayakkulkarni/followers",
    following_url:
      "https://api.github.com/users/vinayakkulkarni/following{/other_user}",
    gists_url: "https://api.github.com/users/vinayakkulkarni/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/vinayakkulkarni/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/vinayakkulkarni/subscriptions",
    organizations_url: "https://api.github.com/users/vinayakkulkarni/orgs",
    repos_url: "https://api.github.com/users/vinayakkulkarni/repos",
    events_url: "https://api.github.com/users/vinayakkulkarni/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/vinayakkulkarni/received_events",
    type: "User",
    site_admin: false,
    name: "Vinayak Kulkarni",
    company: "@GeoSpoc",
    blog: "https://vinayakkulkarni.dev",
    location: "Pune, India",
    email: null,
    hireable: true,
    bio: "Never stop learning, cause life never stops teaching.\r\n\r\n❤️ FOSS",
    twitter_username: "_vinayak_k",
    public_repos: 185,
    public_gists: 35,
    followers: 191,
    following: 421,
    created_at: "2016-06-06T11:30:54Z",
    updated_at: "2021-08-22T16:03:43Z",
  },
];
